### ISSUE TITLE
Cannot build

### ISSUE THREAD

**Issue by IgorGanapolsky** [MindscapeHQ/raygun4android#17]
Hello,
after following your instructions for Gradle dependencies, I get this compilation error:
> Dependency com.mindscapehq.android:raygun4android:1.2.0 on project Application resolves to an APK archive which is not supported as a compilation dependency. File: C:\Users\Igor\.gradle\caches\modules-2\files-2.1\com.mindscapehq.android\raygun4android\1.2.0\762ffb14c64e8dffedf6ac6f0431d83755caefc3\raygun4android-1.2.0.apk

Please advise,
Igor

**Comment by fundead** [comment]
Hi Igor,

It appears there has been an update or some breaking change which has made the previous method not work. We are investigating this, but would you mind trying this in your build.gradle:

```
dependencies {
    compile 'com.google.code.gson:gson:2.1'
    compile 'com.mindscapehq.android:raygun4android:1.3.0:sources'
```

Regards,

Callum Gavin
Mindscape Limited

**Comment by IgorGanapolsky** [comment]
Yes, it works.  Thank you.
