### ISSUE TITLE
Android 6.0 Support

### ISSUE THREAD

**Issue by monesprit54** [MindscapeHQ/raygun4android#19]
Android 6.0 ( M ) does not support Apache Http Library anymore.
The documentation suggests to use HttpUrlConnection implementation instead.
You can still use Apache library by changing build file to use legacy Apache library, but it's just a temporary resolution.
Since Raygun is not supporting Android 2.2 or under, remove dependency on Apache Http library can be done without any dependency problems.

Check out the following link.

http://developer.android.com/preview/behavior-changes.html#behavior-apache-http-client

**Comment by maknz** [comment]
:+1:, godspeed.

**Comment by fundead** [comment]
Thanks for reporting this issue; I can now report that this provider has been updated to remove the deprecated Apache HTTP library in the latest v2.0.0 release.

This release also includes changes to update the archival system to use the latest AAR as expected by Android Studio, Gradle and android-maven-plugin. The README contains updated instructions for referencing the latest release in your build.gradle if you are using that build system. v2.0.0 has now been deployed to Maven Central and is propagating, this normally takes a max of 24 hours to become usable by clients.

Regards,

Callum Gavin
Raygun Limited

**Comment by jihlee** [comment]
:+1: Thanks guys
