### ISSUE TITLE
Add an OnBeforeSend hook for mutating/cancelling an exception report

### ISSUE THREAD

**Issue by jamiepenney** [MindscapeHQ/raygun4android#20]

**Comment by AndyFrench** [comment]
This would definitely be useful. 
Needs to be able to connect with the standard attached UncaughtExceptionHandler though. Adding an interface with `onBeforeSend()` method to affected classes and then attaching implementing class mapping to `RaygunClient` perhaps..?
eg 
    MyClass implements BeforeSendMutator {
        ...
        public void onBeforeSend() {
            RaygunClient.addTags("Relevant data");
        }
    }

    MyApplication extends Application {
        ...
        public void onCreate() {
            RaygunClient.Init(getApplicationContext());
            RaygunClient.AttachExceptionHandler();
            RaygunClient.addBeforeSendMutator(MyClass.class);
        }
    }
