### ISSUE TITLE
Error:(86, 56) error: package main.java.com.mindscapehq.android.raygun4android does not exist

### ISSUE THREAD

**Issue by yumingcui-qochealth** [MindscapeHQ/raygun4android#21]
I am using android studio 1.4.1

build.xml:
buildscript {
    repositories {
        jcenter()
        mavenCentral()
    }
    dependencies {
        classpath 'com.android.tools.build:gradle:1.3.0'
        classpath 'com.neenbedankt.gradle.plugins:android-apt:1.8'
    }
}

Thanks and looking forward to your reply!

**Comment by Morji** [comment]
Having the same issue. Please advise

**Comment by dwnz** [comment]
@yumingcui-qochealth Looking at your build.xml file there, it's appears to be missing a reference to

'com.mindscapehq.android:raygun4android:1.3.0:sources'

If you add that as per the documentation, do you get any further?

**Comment by yumingcui-qochealth** [comment]
Finally make it working with static import the jar file.

**Comment by Morji** [comment]
I don't think this should be closed. I'm still having the issue, even though I'm using the 'com.mindscapehq.android:raygun4android:1.3.0:sources' dependancy.

Yes, importing it as a static jar works, but it's not a fix.

**Comment by mslayton-abra** [comment]
This has been a problem for our builds as well.   However, in our case, adding the 
static jar does not work either.

**Comment by yumingcui-qochealth** [comment]
Hi Valentin,

I finally had that solved with download the jar file and add it to /lib 
and add the following in my android studio.
compile files('lib/raygun4android-1.3.0.jar')

**Comment by fundead** [comment]
This issue and the v1.3 release is out of date and should not be referred to/used, the packaging system was changed to support the expected format of Gradle and Android Studio in v2.x. Please update to the latest v2.1.0 and follow the documentation under Setup Instructions at https://raygun.io/docs/languages/android, and open a new ticket if you're still having issues.

Regards,

Callum Gavin
Raygun Limited
