### ISSUE TITLE
RaygunClient class method spinUpService(String apiKey, String jsonPayload, boolean isPulse) can print user's sensitive data

### ISSUE THREAD

**Issue by Monis1** [MindscapeHQ/raygun4android#35]
RaygunClient class method spinUpService(String apiKey, String jsonPayload, boolean isPulse) can print user's sensitive data using System.out.println, this line should be removed from the method.

**Comment by Monis1** [comment]
This issue got fixed in version 3.0.3.

**Comment by CmdrKeen** [comment]
Thanks for raising the issue @Monis1 👍
