### ISSUE TITLE
Provider has version 3.0.0 hardcoded

### ISSUE THREAD

**Issue by TheRealAgentK** [MindscapeHQ/raygun4android#39]
RaygunClientMessage line 10:

setVersion("3.0.0");

Expected: Always gets set to the current version of the provider. Ideally should be pulled from pom/manifest at runtime.

**Comment by TheRealAgentK** [comment]
Something like this should do that:

```
String version = <SomeRaygunClass>.class.getPackage().getImplementationVersion();
if (version != null) {
    return version;
} else {     
    return "";
}
```

I use the above in another O/S project just fine, but it seems that depending on how you build, implementationVersion doesn't get set/retrieved properly by default (https://stackoverflow.com/questions/2712970/get-maven-artifact-version-at-runtime). Not sure if that'd be a problem for how RG4A is being built.

**Comment by mduncan26** [comment]
Something we wish to address in 4.0? @TheRealAgentK

**Comment by TheRealAgentK** [comment]
It's already pulling that automatically from the build config now: 

https://github.com/MindscapeHQ/raygun4android/commit/daa9e4db07ad59e656372faafb4425410ec84726
