### ISSUE TITLE
App has stopped dialog shown on Android devices when calling Raygun.send()

### ISSUE THREAD

**Issue by nickwri** [MindscapeHQ/raygun4android#44]
Hi,
I'm doing maintenance on an app (which has been using Raygun successfully for a year now), and every time I do a Raygun.send I get a dialog pop up with "Unfortunately, {app-name] has stopped". Its a modal dialog which clears when I click OK, but the app is never stopped i.e. it hasn't crashed, and continues to work fine.

It happens with both debug and release builds, and nothing reaches my Raygun console. I've also tried 2 different api keys, both show the issue. I've also tried an api key from another app (which works within the other app). The Android logcat screen doesn't show any errors, just the I/System.out: message detailing the attempt to send the message.

Raygun version is 3.0.2 (also tried 3.0.0) and compileSDKVersion is 27 (both of these are used in another app which works ok).

I've also reviewed all method calls on RaygunClient - I make one call to init and attachExceptionHandler in my Application class, and the rest are all send calls.

Is there a quick easy explanation for this?

**Comment by nickwri** [comment]
Problem appears to be connected with Firebase. In my app I'm requesting a device token during app startup (in Application), and this is causing the raygunpostservice to generate a FCM initialisation error:

Unable to create application myapp.global.AppMain: java.lang.IllegalStateException: Default FirebaseApp is not initialized .... Make sure to call FirebaseApp.initializeApp(Context) first.

Turns out you don't actually need to request a token (it'll trigger onNewToken in the FCMListener service. However, there does seem to be a clash here somewhere?

**Comment by TheRealAgentK** [comment]
@nickwri Is there a way you could provide a minimum sample app showing the problem for me to have a look at and use for debugging and tracing the issue?

**Comment by mduncan26** [comment]
This issue has been addressed in the latest version of Raygun4Android (v3.0.6). Closing this issue.

**Comment by mduncan26** [comment]
Closing this issue for now. If you wish to see this issue addressed please create a new issue or post within our forums (https://raygun.com/forums). Thank you.
