### ISSUE TITLE
CrashReportingOnBeforeSend is not public

### ISSUE THREAD

**Issue by AndriiVovkWorkspot** [MindscapeHQ/raygun4android#63]
Consequently RaygunClient.setOnBeforeSend() method can't be used.

**Comment by TheRealAgentK** [comment]
Thx for reporting this, @AndriiVovkWorkspot - Which version of the provider are you using?

**Comment by TheRealAgentK** [comment]
Ignore my question, this is an issue of 4.0.0 only afaics

**Comment by TheRealAgentK** [comment]
Thx @AndriiVovkWorkspot , this is fixed in my dev build and will go out to a 4.0.1 release in the next few days.
