### ISSUE TITLE
R8 map center support

### ISSUE THREAD

**Issue by nickwri** [MindscapeHQ/raygun4android#67]
The Raygun dashboard for my app does not have an option to upload an R8 mapping file. Will Raygun support this in the near future like it currently does for Proguard?

**Comment by TheRealAgentK** [comment]
Hi @nickwri. Thx for reporting this - I've passed it on to RG's backend team for now and they're looking into it.

I'll update the issue when I hear back from them.

**Comment by TheRealAgentK** [comment]
Hey @nickwri - sorry for the delay in getting back to you on this. Question - have you tried to upload a mapping file created by R8 into the Proguard mapping uploader? And if so, did that work for you?

**Comment by CmdrKeen** [comment]
Hi @nickwri 

We support R8. It turns out we supported it all along with the Proguard support, but have tightened it up now and will improve the docs here.

Closing this off now.
