### ISSUE TITLE
Including raygun forces apps to use Timber or suffer a million lint warnings.

### ISSUE THREAD

**Issue by DanFTRX** [MindscapeHQ/raygun4android#69]
Timber appears to have several embedded lint rules, of which one is particularly annoying.  The LogNotTimber lint rule which gets inherited by anybody including Raygun, causes all uses of Log to have a lint warning that it should be using Timber.
This cannot be easily worked around, as Android Studio Code inspection profiles are per computer and not something that can be commited into a shared code repository.

I don't think we should have to use Timber in order to use raygun.

**Comment by TheRealAgentK** [comment]
Todos:

- Document excluding the warnings
- Make use of Timber optional maybe

**Comment by TheRealAgentK** [comment]
Fixed in master
