### ISSUE TITLE
Run `CrashReportingPostService` in main process

### ISSUE THREAD

**Issue by jukiginanjar** [MindscapeHQ/raygun4android#74]
Hi team,

```
<service android:name="com.raygun.raygun4android.services.CrashReportingPostService"
            android:exported="false"
            android:permission="android.permission.BIND_JOB_SERVICE"
            android:process=":crashreportingpostservice"/>
```

Is it safe if I remove `android:process=":crashreportingpostservice` so `CrashReportingPostService` will run only in main process? My intention is, I want to make sure my Application only runs in one process, Pls advise.

Thanks.

**Comment by TheRealAgentK** [comment]
@jukiginanjar 

While you could _probably_ do that, I'd generally advise against that approach. 

The most important reason is that you'd want your crash reporting service to be in its own process and to be as independent as possible from any other process of your app. If your app process dies crashes for whatever reason, that gives the crash reporting service a better chance to do its thing and send the crash information to the RG backend.

**Comment by jukiginanjar** [comment]
Got it, thanks
