### ISSUE TITLE
Manually setting version on RaygunClient can break mapping.

### ISSUE THREAD

**Issue by tagy** [MindscapeHQ/raygun4android#80]
If I do not set the version on the Raygun client and upload a mapping file matching the version eg '1.5.2.txt' the stack trace is de-obfuscated as expected.

However if I set the version manually to provide more information, name & version code eg:

`RaygunClient.setVersion("${BuildConfig.VERSION_NAME} (${BuildConfig.VERSION_CODE})")`

The crash report will show the version as I set manually eg: 1.5.2 (452)
But uploading a file '1.5.2 (452).txt' does not de-obfuscate any future crash reports.

This did work as expected in a previous version. 

I have changed how I name the version to the following:

`RaygunClient.setVersion("${BuildConfig.VERSION_NAME}_${BuildConfig.VERSION_CODE}")`

 eg 1.5.2_452 and this does work uploading a file '1.5.2_452.txt'. 

This solves it for me, but adding this incase anyone else has the same issue, I'm not sure if this file name should not contain spaces?

**Comment by TheRealAgentK** [comment]
Thanks for reporting this, @tagy.

@mduncan26 Would you mind checking into the file name expectations when processing mapping files on the backend through the website? The client-side code for setting the version hasn't changed for quite a while.

**Comment by QuantumNightmare** [comment]
Thanks heaps for pointing this out and apologies for the rather late reply. We've tracked down a bug that was introduced at our end causing this issue. A fix for this has recently been deployed that means version numbers with spaces are now supported again. Any mapping files previously uploaded with a space will correctly be applied to newly sent crash reports with the matching version - no need to re-upload mapping files.
